ARG PG_VERSION=16
FROM postgres:${PG_VERSION}

RUN apt-get update && apt-get install -y --no-install-recommends \
      postgresql-${PG_MAJOR}-hypopg \
      postgresql-contrib \
 && rm -rf /var/lib/apt/lists/*

COPY postgresql.test.conf /etc/postgresql/postgresql.conf
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
